
spring:
  datasource:
    url: jdbc:mysql://121.196.233.225:3306/park?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: ?rrq,oq),8cX
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none # 表内有数据时不会清空, 只会更新
    # 控制台显示SQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000  # 连接超时时长（毫秒）


logging:
  level:
    com:
      zk: info
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

app:
  auth:
    key-of-auth: authorized
    expire: 1000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /api-docs
